// react-donut-store/src/main/layout-main/header-main/HeaderMain.js
import React, { Component } from 'react';
import { Route, Link, NavLink } from 'react-router-dom';
import BR6 from '../../../assets/img/donut-store/BR6.jpg';

const menus = [
  {
    name: 'Trang chủ',
    to: '/',
    exact: true,
  }, {
    name: 'Đặt hàng',
    to: '/dat-hang',
    exact: false,
  }, {
    name: 'Liên Hệ',
    to: '/lien-he',
    exact: false,
  }
];

// Viết như này thể hiện là 1 thẻ jsx,không phải là 1 function
const MenuLink = ({ label, to, activeOnlyWhenExact }) => {
  return (
    <Route path={ to } exact={ activeOnlyWhenExact } children={({match}) => {
        const active = match ? 'active' : '';
        return (
          <li className={`nav-item ${active}`}>
            <Link className='nav-link' to={to}>{label}</Link>
          </li>
        )
      }}
    />
  )
}

class HeaderMain extends Component {

  showMenu = (menus) => {
    let result = null;
    if (menus.length > 0) {
      result = menus.map((menu, index) => {
        return (<MenuLink key={index}
            label={menu.name}
            to={menu.to}
            activeOnlyWhenExact={menu.exact}   
          />
        )
      });
    }
    return result;
  }
  render() {
    return (
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <NavLink className="navbar-brand" to="/">
          <img src={BR6} className="img-thumbnail" style={{ width: 40, padding: 0 }} />
        </NavLink>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon" />
        </button>
        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav mr-auto">
            { this.showMenu(menus) }
          </ul>
          <button className="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </div>
      </nav>
    );
  }
}

export default HeaderMain;

// AngularDonutStore/src/app/main/layout-main/header-main/header-main.component.ts
import { IdentityService } from './../../../core/services/identity.service';
import { NavigationService } from './../../../core/services/navigation.service';
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-header-main',
  templateUrl: './header-main.component.html',
  styleUrls: ['./header-main.component.css']
})
export class HeaderMainComponent implements OnInit {
  currentUser;
  constructor(
    private navigationService: NavigationService,
    private identityService: IdentityService,
  ) {
  }

  ngOnInit() {
    this.currentUser = this.identityService.getCurrentUser();
  }

  navLogin() {
    this.navigationService.navLogin();
  }

  navManagement() {
    this.navigationService.navHomepage();
  }

  navHome() {
    this.navigationService.navHome();
  }

  navOrder() {
    this.navigationService.navOrder();
  }

  navContact() {
    this.navigationService.navContact();
  }

  navDetail() {
    this.navigationService.navDetail();
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#" (click)="navHome()">
    <img src="./assets/img/donut-store/BR6.jpg" class="img-thumbnail" style="width:80px; padding:0px;" />
  </a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#" (click)="navHome()">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" (click)="navOrder()">Order</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" (click)="navContact()">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" (click)="navDetail()">Detail</a>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <div class="form-inline my-2 my-lg-0">
        <button class="btn btn-outline-success my-2 my-sm-0" type="button" *ngIf="!currentUser" (click)="navLogin()">Login</button>
        <button class="btn btn-outline-success my-2 my-sm-0" type="button" *ngIf="currentUser" (click)="navManagement()">Management</button>
    </div>
  </div>
</nav>
