// ngDonutStore/src/app/model/staff/page/staff-list/staff-list.component.ts
import { IdentityService } from './../../../../core/services/identity.service';
import { WorkingCalenderService } from './../../../working-calender/service/working-calender.service';
import { WorkingCalender } from './../../../working-calender/working-calender';
import { StoreService } from './../../../store/service/store.service';
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Staff } from '../../staff';
import { CONFIG } from '../../../../shared/constants/configuration.constant';
import { Subscription } from 'rxjs/Subscription';
import { StaffService } from '../../service/staff.service';
import { SortService } from '../../../../core/services/sort.service';
import { sortByProperty } from '../../../../shared/helpers/data.helper';
import { Store } from '../../../store/store';

declare var $: any;
@Component({
  selector: 'app-staff-list',
  templateUrl: './staff-list.component.html',
  styleUrls: ['./staff-list.component.css']
})
export class StaffListComponent implements OnInit, OnDestroy {

  listStaff: Staff[];
  oldStaff: Staff;
  listStore: Store[];
  listWorkingCalender: WorkingCalender[];
  isAdmin = false;

  requestPage;
  notFoundMessage = '';
  error = {
    isError: false,
    message: ''
  };

  sortDirection = 0;
  currentSortProperty = '';

  params = {
    enabled: '',
    storeId: '',
    workingCalenderId: '',
    page: 0,
    size: CONFIG.PAGE_SIZE,
    sort: 'id,desc'
  }
  enabled = [
    { view: 'Active', value: 'true' },
    { view: 'In-Active', value: 'false' }
  ]

  private subListStaff: Subscription;
  private subSortService: Subscription;
  private subStaff: Subscription;
  private subListStore: Subscription;
  private subListWorkingCalender: Subscription;

  constructor(private storeService: StoreService,
    private workingCalenderService: WorkingCalenderService,
    private staffService: StaffService,
    private identityService: IdentityService,
    private sortService: SortService,
  ) {
    this.subSortService = this.sortService.columnSorted$.subscribe(colName => {
      this.sort(colName);
    });
  }

  ngOnInit() {
    this.findList();
    this.subListStore = this.storeService.findAll()
      .subscribe(response => {
        this.listStore = response;
      });
    this.subListWorkingCalender = this.workingCalenderService.findAll()
      .subscribe(response => {
        this.listWorkingCalender = response;
      });
    this.isAdmin = this.identityService.isAdmin();
  }

  ngOnDestroy(): void {
    if (this.subListStaff)
      this.subListStaff.unsubscribe();
    if (this.subSortService)
      this.subSortService.unsubscribe();
    if (this.subStaff)
      this.subStaff.unsubscribe();
    if (this.subListStore)
      this.subListStore.unsubscribe();
    if (this.subListWorkingCalender)
      this.subListWorkingCalender.unsubscribe();
  }

  onFilter() {
    this.params.page = 0;
    this.findList();
  }

  findList() {
    this.subListStaff = this.staffService.findList(this.params)
      .subscribe(response => {
        this.error.isError = false;
        this.listStaff = response.content;
        if (this.listStaff.length === 0) {
          this.notFoundMessage = "We're not found any contents";
        } else {
          this.notFoundMessage = "";
        }
        this.requestPage = response;
      }, error => {
        this.error.isError = true;
        this.error.message = error.error;
      })
  }

  sort(property: string) {
    if (this.currentSortProperty === '') {
      this.currentSortProperty = property;
    }
    if (this.currentSortProperty !== property) {
      this.sortDirection = 0;
      this.currentSortProperty = property;
    }
    this.sortDirection = (this.sortDirection === 0) ? 1 : (this.sortDirection === 1) ? -1 : 0;
    this.listStaff.sort(sortByProperty(property, this.sortDirection));
  }

  first() {
    if (!this.requestPage.first) {
      this.params.page = 0;
      this.findList();
    }
  }

  prev() {
    if (!this.requestPage.first) {
      this.params.page = this.requestPage.number - 1;
      this.findList();
    }

  }

  next() {
    if (!this.requestPage.last) {
      this.params.page = this.requestPage.number + 1;
      this.findList();
    }
  }

  last() {
    if (!this.requestPage.last) {
      this.params.page = this.requestPage.totalPages - 1;
      this.findList();
    }
  }

  openModal() {
    $('#modal_add_staff').modal({ show: true, backdrop: 'static' });
  }

  staffSubmitted(event) {
    if (event === 'success') {
      this.params.page = 0;
      // reload request list
      this.findList();
      // close modal
      $('#modal_add_staff').modal('toggle');
    }
  }

  staffUpdated(event) {
    if (event === 'success') {
      this.params.page = 0;
      // reload request list
      this.findList();
      // close modal
      $('#modal_update_staff').modal('toggle');
    }
  }

  onDetail(staff) {
    this.oldStaff = staff;
    this.staffService.setStaff(JSON.parse(JSON.stringify(staff)));
    $('#modal_update_staff').modal({ show: true, backdrop: 'static' });
  }

  onEnabledOrNot(id) {
    this.subStaff = this.staffService.enabledOrNot({ id: id })
      .subscribe(response => {
        this.error.isError = false;
        this.findList();
      }, error => {
        this.error.isError = true;
        this.error.message = error.error;
      })
  }

}

<div class="m-grid__item m-grid__item--fluid m-wrapper">
  <!-- BEGIN: Subheader -->
  <div class="m-subheader">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="m-subheader__title m-subheader__title--separator">
          Staff
        </h3>
        <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
          <li class="m-nav__item m-nav__item--home">
            <a href="#" class="m-nav__link m-nav__link--icon">
              <i class="m-nav__link-icon la la-home"></i>
            </a>
          </li>
          <li class="m-nav__separator">
            -
          </li>
          <li class="m-nav__item">
            <a href="javascript: void(0);" class="m-nav__link">
              <span class="m-nav__link-text">
                List Staff
              </span>
            </a>
          </li>
          <li class="m-nav__separator">
            -
          </li>
          <li class="m-nav__item">
            <a href="javascript: void(0);" class="m-nav__link">
              <span class="m-nav__link-text">
                List
              </span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- END: Subheader -->
  <div class="m-content">
    <div class="row">
      <div class="col-12">
        <div class="m-portlet">
          <div class="m-form__content">
            <div class="m-alert m-alert--icon alert alert-danger" *ngIf="error.isError" role="alert">
              <div class="m-alert__icon">
                <i class="la la-warning"></i>
              </div>
              <div class="m-alert__text">
                {{ error.message }}
              </div>
              <div class="m-alert__close">
                <button type="button" class="close" data-close="alert" aria-label="Close"></button>
              </div>
            </div>
          </div>
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  <span *ngIf="listStaff"> List Staff </span>
                </h3>
              </div>
            </div>
            <div class="m-portlet__head-tools">
              <button _ngcontent-c7="" class="btn btn-success m-btn--icon m-btn--air" type="button" (click)="openModal()">
                <span _ngcontent-c7="">
                  <i _ngcontent-c7="" class="la la-plus"></i>
                  <span _ngcontent-c7="">
                    New Staff
                  </span>
                </span>
              </button>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <!-- FILTER -->
                <div class="row">
                  <div class="col-12 col-sm-6 col-md-3">
                    <div class="form-group m-form__group">
                      <div class="input-group">
                        <select class="form-control" [(ngModel)]="params.enabled">
                          <option value="">Select Enabled</option>
                          <option *ngFor="let e of enabled" [value]="e.value">{{ e.view }}</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-sm-6 col-md-3" *ngIf="isAdmin">
                    <div class="form-group m-form__group">
                      <div class="input-group">
                        <select class="form-control" [(ngModel)]="params.storeId">
                          <option value="">Select Store</option>
                          <option *ngFor="let store of listStore" [value]="store?.id">{{ store?.name }}</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-sm-6 col-md-3">
                    <div class="form-group m-form__group">
                      <div class="input-group">
                        <select class="form-control" [(ngModel)]="params.workingCalenderId">
                          <option value="">Select Working Calender</option>
                          <option *ngFor="let workingCalender of listWorkingCalender" [value]="workingCalender?.id">{{ workingCalender?.name }}</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-sm-6 col-md-3">
                    <div class="float-right">
                      <button type="button" class="btn btn-info m-btn m-btn--icon" (click)="onFilter()">
                        <span>
                          <i class="la la-filter"></i>
                          <span>
                            Filter
                          </span>
                        </span>
                      </button>
                    </div>
                  </div>
                </div>
                <!-- END FILTER -->
                <!-- TABLE -->
                <table class="table table-responsive table-bordered table-hover m-table m-table--head-bg-info">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th sortable-column="name">Name</th>
                      <th sortable-column="picture">Picture</th>
                      <th sortable-column="storeId.name">Store</th>
                      <th sortable-column="dateCreated">Date Created</th>
                      <th sortable-column="dateUpdated">Date Updated</th>
                      <th sortable-column="phone">Phone</th>
                      <th sortable-column="address">Address</th>
                      <th sortable-column="identityCard">Identity Card</th>
                      <th sortable-column="homeTown">Home Town</th>
                      <th sortable-column="salary">Salary</th>
                      <th sortable-column="workingCalenderId">Working Calender</th>
                      <th sortable-column="enabled">Enabled</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <!-- END::SHOW MESSAGE -->
                  <tbody *ngIf="listStaff && listStaff?.length > 0">
                    <tr *ngFor="let staff of listStaff; let i = index;">
                      <th scope="row">{{ requestPage.size * requestPage.number + i + 1 }}</th>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.name }}">{{ staff?.name | summary: 20}}</span>
                      </td>
                      <td>
                        <img width="200" [src]="staff?.picture" />
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.storeId.name }}">{{ staff?.storeId.name | summary: 20 }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.dateCreated }}">{{ staff?.dateCreated | date }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.dateUpdated }}">{{ staff?.dateUpdated | date }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.phone }}">{{ staff?.phone }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.address }}">{{ staff?.address }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.identityCard }}">{{ staff?.identityCard }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.homeTown }}">{{ staff?.homeTown }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.salary }}">{{ staff?.salary }}</span>
                      </td>
                      <td>
                        <span placement="top" ngbTooltip="{{ staff?.workingCalenderId.name }}">{{ staff?.workingCalenderId.name }}</span>
                      </td>
                      <td>
                        <span *ngIf="staff?.enabled" style="color: red">Active</span>
                        <span *ngIf="!staff?.enabled" style="color: black">In-Active</span>
                      </td>
                      <td>
                        <i class="la la-edit" (click)="onDetail(staff)" placement="top" ngbTooltip="View detail">
                        </i>
                        <i class="la la-magic" (click)="onEnabledOrNot(staff?.id)" placement="top" ngbTooltip="Enabled or Disabled">
                        </i>
                      </td>
                    </tr>
                  </tbody>
                </table>
                <!-- END::TABLE -->

                <!-- PAGINATION -->
                <div class="row align-items-end" *ngIf="requestPage?.totalElements > 0">
                  <div class="col-12">
                    <div class="float-right">
                      <div aria-label="Next buttons" class="btn-group btn-group-sm" role="group">
                        <button class="btn btn-outline-info" type="button" (click)="first()" [disabled]="requestPage?.first">
                          <i class="la la-angle-double-left"></i>
                        </button>
                        <button class="m-btn btn btn-outline-info no-border-left" type="button" (click)="prev()" [disabled]="requestPage?.first">
                          <i class="la la-angle-left"></i>
                        </button>
                      </div>
                      <div class="pagination__page-number">
                        <p>Page {{ (requestPage?.totalPages === 0)? 0 : requestPage?.number + 1 }} of {{ requestPage?.totalPages
                          }}
                        </p>
                      </div>
                      <div aria-label="Next buttons" class="btn-group btn-group-sm" role="group">
                        <button class="m-btn btn btn-outline-info" type="button" (click)="next()" [disabled]="requestPage?.last">
                          <i class="la la-angle-right"></i>
                        </button>
                        <button class="btn btn-outline-info no-border-left" type="button" (click)="last()" [disabled]="requestPage?.last">
                          <i class="la la-angle-double-right"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- END::PAGINATION -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal_add_staff" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Create new Staff
        </h5>
      </div>
      <div class="modal-body">
        <app-staff-create [listStore]="listStore" [listWorkingCalender]="listWorkingCalender" [isAdmin]="isAdmin" (submitted)="staffSubmitted($event)"></app-staff-create>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          Done
        </button>
      </div> -->
    </div>
  </div>
</div>
<div class="modal fade" id="modal_update_staff" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Update Staff
        </h5>
      </div>
      <div class="modal-body">
        <app-staff-detail [oldStaff]="oldStaff" [listStore]="listStore" [listWorkingCalender]="listWorkingCalender" (submitted)="staffUpdated($event)"></app-staff-detail>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          Done
        </button>
      </div> -->
    </div>
  </div>
</div>

// react-donut-store/src/management/page/config/model/staff/StaffList.js
import React, { Component } from 'react';
import { findListStaff, showOrNot } from './StaffApiCaller';
import { CONFIG, selectEnabledOption } from '../../../../../share/constant/configuration.constant';
import ReactTooltip from 'react-tooltip';
import CustomSelect from '../../../../../share/common/custom-select/CustomSelect';
// import CustomDate from '../../../../../share/common/custom-datetime/CustomDate';
import * as Helper from '../../../../../share/common/helper/Helper';
import Create from './component/Create';
import Update from './component/Update';
import NumberFormat from 'react-number-format';
import { findAllStore } from '../store/StoreApiCaller';
import { findAllWorkingCalender } from '../working-calender/WorkingCalenderApiCaller';

class StaffList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      listStaff: {},
      listStore: [],
      listWorkingCalender: [],
      params: {
        storeId: '',
        workingCalenderId: '',
        enabled: '',
        page: 0,
        size: CONFIG.PAGE_SIZE,
        sort: 'id,desc'
      },
      updateStaff: undefined,
      isSubmitting: false,
      showModalCreate: false,
      showModateUpdate: false,
    }
  }

  componentDidMount() {
    this.onFilter();
    findAllStore().then(({ data }) => {
      this.setState({
        listStore: data,
      });
    });
    findAllWorkingCalender().then(({ data }) => {
      this.setState({
        listWorkingCalender: data,
      });
    })
  }

  onReceivedSelectValue = (event) => {
    if (!this.state.isSubmitting) {
      this.setState({
        params: Object.assign({}, this.state.params, { [event.name]: event.value })
      })
    }
  }

  onReceivedValue = event => {
    if (!this.state.isSubmitting) {
      this.setState({
        [event.name]: event.value,
      }, () => {
        if (event.refresh)
          this.onFilter();
        if (event.update) {
          this.setState({
            updateStaff: undefined,
          });
          this.updateList(this.state.listStaff.content, event.update);
        }
      })
    }
  }

  onFilter = () => {
    findListStaff(this.state.params).then(({ data }) => {
      this.setState({
        listStaff: data,
      });
    })
  }

  onNew = () => {
    if (!this.state.isSubmitting) {
      this.setState({
        showModalCreate: true,
      })
    }
  }
  onUpdate = (staff) => {
    if (!this.state.isSubmitting) {
      this.setState({
        updateStaff: staff,
        showModalUpdate: true,
      })
    }
  }
  showOrNot = (id) => {
    if (!this.state.isSubmitting) {
      Helper.setLoading(true);
      this.setState({
        isSubmitting: true
      });
      showOrNot(id).then(({ data }) => {
        Helper.setLoading(false);
        this.setState({
          isSubmitting: false
        });
        const list = this.state.listStaff.content;
        this.updateList(list, data);
      }).catch(({ response }) => {
        Helper.setLoading(false);
        this.setState({
          isSubmitting: false
        }, () => alert(response.data));
      })
    }
  }
  updateList = (list, data) => {
    const index = list.findIndex(i => +i.id === +data.id);
    this.setState({
      listStaff: Object.assign({}, this.state.listStaff, {
        content: [].concat(list.slice(0, index)).concat(data).concat(list.slice(index + 1)),
      })
    })
  }
  first = () => {
    if (!this.state.listStaff.first) {
      this.setState({
        params: Object.assign({}, this.state.params, {
          page: 0,
        })
      }, () => {
        this.onFilter();
      });
    }
  }

  prev = () => {
    if (!this.state.listStaff.first) {
      this.setState({
        params: Object.assign({}, this.state.params, {
          page: this.state.listStaff.number - 1,
        })
      }, () => {
        this.onFilter();
      });
    }
  }
  next = () => {
    if (!this.state.listStaff.last) {
      this.setState({
        params: Object.assign({}, this.state.params, {
          page: this.state.listStaff.number + 1,
        })
      }, () => {
        this.onFilter();
      });
    }
  }
  last = () => {
    if (!this.state.listStaff.last) {
      this.setState({
        params: Object.assign({}, this.state.params, {
          page: this.state.listStaff.totalPages - 1,
        })
      }, () => {
        this.onFilter();
      });
    }
  }

  showPagination = () => {
    const { totalPages } = this.state.listStaff;
    return (totalPages) ? (<p>
      Page {(totalPages === 0) ? 0 : this.state.listStaff.number + 1} of {totalPages}
    </p>) : (<p>Page 0 of 0</p>);
  }

  showListStaff = () => {
    const { listStaff } = this.state;
    return (!listStaff.content) ? null : (
      listStaff.content.map((staff, index) => {
        return (
          <tr key={index}>
            <th scope="row">{index}</th>
            <td>{staff.name}</td>
            <td><a href={staff.picture} target="_blank">{staff.picture}</a></td>
            <td>{staff.storeId.name}</td>
            <td>{staff.dateCreated}</td>
            <td>{staff.dateUpdated}</td>
            <td>{staff.phone}</td>
            <td>{staff.address}</td>
            <td>{staff.identityCard}</td>
            <td>{staff.homeTown}</td>
            <td><NumberFormat value={staff.salary} displayType={'text'} thousandSeparator={true} />₫</td>
            <td>{staff.workingCalenderId.name}</td>
            <td>{staff.enabled ? "Yes" : "No"}</td>
            <td>
              <i className="fas fa-exchange-alt" data-tip="Đổi status" style={{ cursor: 'pointer' }} onClick={() => this.showOrNot(staff.id)}></i>  &nbsp;
              <i className="fas fa-edit" data-tip="Sửa" style={{ cursor: 'pointer' }} onClick={() => this.onUpdate(staff)}></i>
            </td>
          </tr>
        );
      })
    );
  }
  render() {
    return (
      <div className="container-fluid">
        <div className="row padding-top1">
          <div className="col-md-9">
            <div className="row">
              <div className="col-md-2">
                <CustomSelect placeholder="Status" name="enabled" value={this.state.params.enabled} required={false}
                  data={selectEnabledOption} onEmittedValue={this.onReceivedSelectValue} />
              </div>
              <div className="col-md-2">
                <CustomSelect placeholder="Store" name="storeId" value={this.state.params.storeId} required={false}
                  data={this.state.listStore} onEmittedValue={this.onReceivedSelectValue} />
              </div>
              <div className="col-md-2">
                <CustomSelect placeholder="Working Calender" name="workingCalenderId" value={this.state.params.workingCalenderId} required={false}
                  data={this.state.listWorkingCalender} onEmittedValue={this.onReceivedSelectValue} />
              </div>
            </div>
          </div>
          <div className="col-md-3">
            <div className="float-right">
              <button type="button" className="btn btn-outline-success" data-tip="Lọc" onClick={this.onFilter}><i className="fas fa-filter"></i></button>&nbsp;
                  <button type="button" className="btn btn-outline-primary" data-tip="Tạo mới" onClick={this.onNew}><i className="fas fa-plus-circle"></i></button>
            </div>
          </div>
        </div>
        <div style={{ overflowX: 'auto' }}>
          <table className="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Picture</th>
                <th scope="col">Store</th>
                <th scope="col">Date Created</th>
                <th scope="col">Date Updated</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">Identity Card</th>
                <th scope="col">Home Town</th>
                <th scope="col">Salary</th>
                <th scope="col">Working calender</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {this.showListStaff()}
            </tbody>
          </table>
        </div>
        <div className="row padding-top1">
          <div className="col-12">
            <div className="float-right">
              <div className="btn-group btn-group-sm" role="group">
                <button type="button" className="btn btn-outline-info" onClick={this.first}><i className="fas fa-angle-double-left"></i></button>
                <button type="button" className="btn btn-outline-info" onClick={this.prev}><i className="fas fa-angle-left"></i></button>
              </div>
              <div className="pagination__page-number">
                {this.showPagination()}
              </div>
              <div className="btn-group btn-group-sm" role="group">
                <button type="button" className="btn btn-outline-info" onClick={this.next}><i className="fas fa-angle-right"></i></button>
                <button type="button" className="btn btn-outline-info" onClick={this.last}><i className="fas fa-angle-double-right"></i></button>
              </div>
            </div>
          </div>
        </div>
        <ReactTooltip />
        {this.state.showModalCreate ? <Create onEmittedCloseModalCreate={this.onReceivedValue} listStore={this.state.listStore} listWorkingCalender={this.state.listWorkingCalender} /> : null}
        {this.state.showModalUpdate ? <Update onEmittedCloseModalUpdate={this.onReceivedValue} staff={this.state.updateStaff} listStore={this.state.listStore} listWorkingCalender={this.state.listWorkingCalender} /> : null}
      </div>
    )
  }
}

export default StaffList;
