// react-donut-store/src/main/component/single-item/SingleItem.js
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';
import './SingleItem.css';

class SingleItem extends Component {

  render() {
    return (
      <div className="col-sm-4">
        <NavLink className="ds-single-item" to="#">
          <div className="ds-single-item-image" style={{backgroundImage: `url(${this.props.item.picture})`}} />
          <h4>{ this.props.item.name }</h4>
          <p>{ this.props.item.description }</p>
          <hr />
          <span>{ this.props.item.singleValue} đ</span>
          <button type="button" className="btn btn-success">Mua ngay</button>
        </NavLink>
      </div>
    );
  }
}

export default SingleItem;

// AngularDonutStore/src/app/main/component/single-item/single-item.component.ts
import { Item } from './../../../management/model/item/item';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-single-item',
  templateUrl: './single-item.component.html',
  styleUrls: ['./single-item.component.css']
})
export class SingleItemComponent implements OnInit {

  @Input('item') item: Item;
  constructor() { }

  ngOnInit() {
  }

}

<a class="ds-single-item" routerLink="#">
  <div class="ds-single-item-image" [ngStyle]="{'background-image': 'url('+item.picture+')'}"></div>
  <h4>{{ item.name }}</h4>
  <p>{{ item.description }}</p>
  <hr>
  <span>
    {{ item.singleValue }} đ
  </span>
  <button type="button" class="btn btn-success">Mua ngay</button>
</a>
